/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appcompradecupones;

/**
 *
 * @author JOSE ENRIQUE
 */
public class Ingresar extends javax.swing.JFrame {

    /**
     * Creates new form ingresar2
     */
    public Ingresar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usuario_lbl = new javax.swing.JLabel();
        usuario_txt = new javax.swing.JTextField();
        contraseña_lbl = new javax.swing.JLabel();
        contraseña_pass = new javax.swing.JPasswordField();
        ingresar_btn = new javax.swing.JButton();
        registrarse_lbl = new javax.swing.JLabel();
        recuperar_lbl = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        titulo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_lbl.setText("Inicio de Sesión");
        titulo_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(titulo_lbl, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        usuario_lbl.setText("Usuario");
        usuario_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 97);
        jPanel1.add(usuario_lbl, gridBagConstraints);

        usuario_txt.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(usuario_txt, gridBagConstraints);

        contraseña_lbl.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 75);
        jPanel1.add(contraseña_lbl, gridBagConstraints);

        contraseña_pass.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(contraseña_pass, gridBagConstraints);

        ingresar_btn.setText("Ingresar");
        ingresar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(ingresar_btn, gridBagConstraints);

        registrarse_lbl.setForeground(new java.awt.Color(0, 51, 255));
        registrarse_lbl.setText("Registrarse");
        registrarse_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarse_lblMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(registrarse_lbl, gridBagConstraints);

        recuperar_lbl.setForeground(new java.awt.Color(0, 51, 255));
        recuperar_lbl.setText("Recuperar Contraseña");
        recuperar_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recuperar_lblMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(recuperar_lbl, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_btnActionPerformed

    private void registrarse_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarse_lblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarse_lblMouseClicked

    private void recuperar_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperar_lblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_recuperar_lblMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña_lbl;
    private javax.swing.JPasswordField contraseña_pass;
    private javax.swing.JButton ingresar_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel recuperar_lbl;
    private javax.swing.JLabel registrarse_lbl;
    private javax.swing.JLabel titulo_lbl;
    private javax.swing.JLabel usuario_lbl;
    private javax.swing.JTextField usuario_txt;
    // End of variables declaration//GEN-END:variables
}
